Farming WIP
crystallpunk-14/crystall-punk-14 pull request #269
Opened 2024-06-23 15:16 UTC by TheShuEd

2024-06-25 13:14 UTC, Tornado-Technology requested changes
Это было тяжело, подмечено далеко не все из-за размеров кода. Попроси снова ревью как закончишь с этим :P

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Shared/_CP14/Farming/CP14SharedFarmingSystem.cs
> +public partial class CP14SharedFarmingSystem : EntitySystem
`Class must be explicitly marked as [Virtual], abstract, static or sealed`, это в данном случаи `abstract`

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.cs
> +            var newTime = TimeSpan.FromSeconds(plant.UpdateFrequency);
Вот из-за этого я тебя прошу использовать в компонентах `TimeSpan`, при серелизации из прототипов он все равно берет время в секундах по умолчанию

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.cs
> +            var energyEv = new CP14PlantEnergyUpdateEvent();
Зачем тебе в принципе столько приколов, если ты можешь в 1 `Update` ивент загрузить информацию о дополнительной энергии и `Canceled` в твоем случае будет приравнивание `Energy = 0` как и `CP14PlantResourceUpdateEvent`

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.cs
> +            Dirty(new Entity<CP14PlantComponent>(uid, plant));
Не обязательно так, ты можешь спокойно написать  `Dirty(uid, plant);`

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Tools.cs
> +        if (EntityManager.EntityExists(soilComp.PlantUid))
Просто используй `Exists`

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Tools.cs
> +            if (user != null)
Подмечу только здесь, но лучше используй `is not null`, если интересно почему. напиши в дискорде.

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Resourse.cs
> +        var metabolizer = _proto.Index(ent.Comp.Metabolizer);
Эта хуйня может тебе выкинуть исключение, уверен, что тебе это надо?

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Resourse.cs
> +                effect.Effect(new Entity<CP14PlantComponent>(ent, plant), reagent.Quantity);
А разве `(ent, plant)` не сработает?

2024-06-25 13:14 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Resourse.cs
> +            if (!metabolizer.Metabolization.ContainsKey(reagent.Reagent.ToString()))
Почему не `Id`?

Мы же фактически получаем `Data?.ToString(Prototype, quantity) ?? $"{Prototype}:{quantity}"`, зачем нам количество?

2024-06-25 13:22 UTC, TheShuEd commented on Content.Server/_CP14/Farming/Components/CP14PlantGrowingComponent.cs
> +///
На самом деле я еще часть фич не реализовал. И комменты тут наоборот, появятся

2024-06-25 13:25 UTC, TheShuEd commented on Content.Shared/_CP14/Farming/Prototypes/CP14PlantMetabolizerPrototype.cs
> +    public Dictionary<ProtoId<ReagentPrototype>, List<CP14MetabolizerEffect>> Metabolization = new();
в чем разница между List и HashSet?

2024-06-26 12:43 UTC, Tornado-Technology commented on Content.Shared/_CP14/Farming/Prototypes/CP14PlantMetabolizerPrototype.cs
> +    public Dictionary<ProtoId<ReagentPrototype>, List<CP14MetabolizerEffect>> Metabolization = new();
Блять

2024-07-05 14:41 UTC, Tornado-Technology approved these changes
Есть мелкие недочёты, но дума. лучше будет добавить issuse их рефактор, чем 100 раз все переделывать, од очень большой и охватить его чисто из веб клиента сложновато

2024-07-05 14:41 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Interactions.cs
> +            if (tag != "All")
создай `private static readonly ProtoId<TagPrototype>` поле, такие поля автоматически проверяются на валидность тэгов

2024-07-05 14:41 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Interactions.cs
> +            result.Add(Spawn(spawnLoot[0], spawnPos)); //TODO почему то не спавнится больше 1 пшенички. Кажись проблема оффов
не делаешь проверку что `spawnLoot.Count > 0`

2024-07-05 14:41 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Interactions.cs
> +            var getLoot = _proto.Index(table);
Если, что это может выкинуть эксепшен

2024-07-05 14:41 UTC, Tornado-Technology commented on Content.Server/_CP14/Farming/Components/CP14PlantFadingComponent.cs
> +        DamageDict = new Dictionary<string, FixedPoint2>
Не `string`, а `ProtoId<DamageTypePrototype>`

2024-07-05 14:41 UTC, Tornado-Technology commented on Content.Shared/_CP14/Farming/CP14PlantGatherableComponent.cs
> +    public EntityWhitelist? ToolWhitelist;
Почему `required`, если тип может быть равен `null`?

2024-07-05 15:00 UTC, TheShuEd commented on Content.Server/_CP14/Farming/CP14FarmingSystem.Interactions.cs
> +            if (tag != "All")
это литералли копирка кода GatheringSystem оффов, не хочу менять, не моя иссуе.

Я потом скорее оффам подправлю эту системку, и ее реюзну

2024-07-15 20:41 UTC, TheShuEd commented on Content.Server/_CP14/Farming/Components/CP14PlantFadingComponent.cs
> +        DamageDict = new Dictionary<string, FixedPoint2>
не
![image](https://github.com/user-attachments/assets/a37c80f0-4367-497d-8084-d49eaf368a66)

2024-07-15 20:58 UTC, merged