Add beards
crystallpunk-14/crystall-punk-14 pull request #312
Opened 2024-07-07 06:38 UTC by ravage123321

borodi

## About the PR
Я добавил много бород

## Why / Balance
Нам нужно больше бород

## Media
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/142820619/1bacdd07-2bd4-466b-901c-2547166f8e00)

2024-07-07 06:39 UTC, ravage123321 commented
Мету я не менял, потому что я рисовал бороды с прототипов в интернете, но думаю, что половина из них есть в игре так же, а какие определять не хочу :(

И надо будет наверное поменять название пару бород, если текущие не понравятся. Я их называл почти наугад

2024-07-07 09:54 UTC, TheShuEd requested changes
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/fc4b35c9-a5f2-4e33-abb7-9c95fbb100fa)
"Шорты" сбоку выглядят ниже чем спереди
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/fb2c71a0-d774-48c4-bc84-a59ceb32c946)

и в целом почти все бороды сбоку выглядят не так как ожидается. Например "Мачете":
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/56536cc0-3aa1-40e4-9461-96823000da27)
Здесь 3 верхних пикселя по ширине на уровне глаз
в то время как с виду сбоку, мы все еще видим оба глаза, но борода уехала куда-то на другуюю сторону лица.
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/3409f6ba-001e-4f85-b658-d38f9c9ecee0)

2024-07-07 11:13 UTC, ravage123321 commented
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/142820619/8b4366cb-3f76-4f02-be6b-a360c9dbc171)
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/142820619/a5d4b849-43f6-4ce4-bf15-2865192e48e3)

2024-07-07 11:14 UTC, TheShuEd commented
Да, то что надо

2024-07-08 11:21 UTC, TheShuEd approved these changes

2024-07-08 11:21 UTC, merged