Some prototypes
crystallpunk-14/crystall-punk-14 pull request #349
Opened 2024-07-23 11:42 UTC by GrandApothecary19

## About the PR
Немного подправлены стейты у костра(один стейт был пропущен, теперь будет отображаться при полном наполнении костра)
Добавлено:
1. Большая деревянная бочка
2. Жир(для свечей)
3. Свечи(стальные и латунные, в том числе и сдвоенные)

Великолепные спрайты рисовал @Jaraten

2024-07-23 11:45 UTC, Jaraten commented
WIP, позже доделаю недостающее, со спрайтами огня и перестановкой жира в objects.

2024-07-28 14:57 UTC, TheShuEd requested changes

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/candle.yml
> +  parent: CP14BaseFireplace
Все свечи стоит сделать предметами, которые можно переносить, сейчас они еще и к центру тайла прикреплены, что не подвинуть никуда.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/candle.yml
> +  - type: CP14FireSpread
свечи не должны ничего поджигать, это вообще крашило билд с 0 значением, лол.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
> +    .desc = слишком  много  жира  может  привести к  ожирению.
С большой буквы + лишние пробелы.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/fat.yml
> +  id: CP14Fat1
должен быть Flammable, чтобы fireplaceSystem могла поглощать его.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/big_barrel.yml
> +  - type: Drink
Пить напрямую из такой гигантской бочки?

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/big_barrel.yml
> +  - type: SolutionContainerVisuals
Бездумное копирование компонентов, которые не имеют смысла.

SolutionContainerVisuals позволяет визуализировать на объекте заполненность жидкостями разных степеней. В этой бочке попросту не видно ничего по спрайту.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/big_barrel.yml
> +      - !type:SolutionExplosionBehavior
Зачем бочке взрываться .-.

накопировано с fuelTank явно, много лишнего в прототипе

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/candle.yml
> +    radius: 0 # Радиус возможно надо будет вернуть, пока убрал.
Не должны свечи поджигать столы и пол, на которых стоят. Это можно убрать.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/candle.yml
> +  id: CP14SteelCandle
Свечи попросту не поджигаются сейчас, и у них нет спрайтов горения.

2024-07-28 14:57 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/candle.yml
> +    radius: 0 # Радиус возможно надо будет вернуть, пока убрал.
так же не нужно

2024-08-19 15:45 UTC, TheShuEd commented
о_о
ПР жив?

2024-08-22 10:09 UTC, TheShuEd commented
Если вы решите продолжить работу над этим, напишите комментарий, и ПР откроется.

2024-08-22 10:09 UTC, closed without merging

2024-09-01 14:35 UTC, GrandApothecary19 commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/candle.yml
> +  id: CP14SteelCandle
Спрайты горения должен был джаратен сделать, так что тут не могу помочь.