More sprites for tavern
crystallpunk-14/crystall-punk-14 pull request #357
Opened 2024-07-25 19:44 UTC by GrandApothecary19

## About the PR
Спрайты для таверны

1. 4 вида кружек
2. 5 видов бутылок
3. Мясо(сырое и приготовленное)
4. Разделочная доска

Спрайты от @omsoyk

P.S. Доска просто как предмет без возможностей. Бутылки не обязательно для таверны, там среди них еще 2 маленькие(флаконы) можно для чего-то еще использовать.

2024-07-28 15:14 UTC, TheShuEd requested changes
спрайты охренительны, но прототипы требуют доработки

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/bottles.yml
> +  name: Green Bottle
Делая все эти бутылки лучше ориентироваться на существующие склянки для зелий, т.к. здесь немного изменена система обращения с жидкостями. Но пробки оставить.

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/bottles.yml
> +  parent: [DrinkBottleVisualsAll, DrinkBottleGlassBaseFull]
Так же 100u для бутылки чот дофига. У нас Малая склянка для зелий имеет емкость в 10u, бутылки должны иметь, ну, 20-30 максимум, и занимать больше места в инвентаре иначе это будет имбово.

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/mugs.yml
> +  - type: PhysicalComposition
Это лишнее, мы этим не пользуемся

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/mugs.yml
> +  - type: PhysicalComposition
аналогично

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/mugs.yml
> +  - type: PhysicalComposition
аналогично

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/mugs.yml
> +  - type: PhysicalComposition
аналогично

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/meat.yml
> +  id: CP14RawFoodMeat
![image](https://github.com/user-attachments/assets/732a8138-ac6a-4f08-aa48-7633bad7922d)
после готовки превратилось не в то мясо

2024-07-28 15:14 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Structures/Furniture/cutting_board.yml
> +  id: CP14CuttingBoard
![image](https://github.com/user-attachments/assets/5142ce30-ca4e-4072-b049-570bf9f4aef3)
стоит перевернуть спрайт в инвентаре или лучше сделать 2 на 2

2024-07-31 17:58 UTC, GrandApothecary19 commented
Так-с, ну вроде все исправлено. Разве что не уверен насчет бутылок, стандартный размер 2х1 подойдет? Или лучше сделать 2х2?

2024-07-31 18:18 UTC, TheShuEd commented
2x1 ок

2024-08-03 12:51 UTC, TheShuEd approved these changes

2024-08-03 12:51 UTC, merged