LongBow
crystallpunk-14/crystall-punk-14 pull request #374
Opened 2024-07-31 17:35 UTC by DenaUxUi

LongBow from Dena_

## About the PR

Added LongBow without craft recipe
Добавлен Длинный Лук без рецепта крафта

## Why / Balance

Added new weapon
Добавлено новое оружие

## Media

https://github.com/user-attachments/assets/d14247c1-7cd9-4452-9110-f49e1a9d195e

2024-08-01 08:26 UTC, TheShuEd requested changes

2024-08-01 08:26 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Weapons/Ranged/longBow.yml
> +  description: Long-bow
Change description to more interesting please

2024-08-01 08:26 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Objects/Weapons/Ranged/longBow.yml
> +  name: LongBow
no uppercase in names

2024-08-01 08:48 UTC, Jaraten requested changes
Work on light shading and shape.

2024-08-01 08:48 UTC, Jaraten commented on Resources/Textures/_CP14/Objects/Weapons/Ranged/longbow.rsi/inhand-left.png
sprite in hand doesn't look good, better to tweak it for perspective.
![Снимок экрана 2024-08-01 113344](https://github.com/user-attachments/assets/25b4fbb2-f645-4185-900d-228a0c37cd26)

2024-08-01 08:48 UTC, Jaraten commented on Resources/Textures/_CP14/Objects/Weapons/Ranged/longbow.rsi/inhand-right.png
Same fault as above

2024-08-01 08:48 UTC, Jaraten commented on Resources/Textures/_CP14/Objects/Weapons/Ranged/longbow.rsi/unwielded-arrow.png
arrow sprite looks flat, add shadows and lights

2024-08-01 08:48 UTC, Jaraten commented on Resources/Textures/_CP14/Objects/Weapons/Ranged/longbow.rsi/wielded-inhand-left.png
![image](https://github.com/user-attachments/assets/48d99de7-bf6e-4962-a566-a0546918ba03)
the form is very strange and messy

2024-08-01 08:48 UTC, Jaraten commented on Resources/Textures/_CP14/Objects/Weapons/Ranged/longbow.rsi/wielded-inhand-right.png
> the form is very strange and messy

same

2024-08-01 08:48 UTC, Jaraten commented on Resources/Textures/_CP14/Objects/Weapons/Ranged/longbow.rsi/equipped-BACKPACK.png
![image](https://github.com/user-attachments/assets/7bdc3df1-7ad9-4aa2-bffc-44c7a2a265c7)
back sprite looks incomplete.

2024-08-22 10:10 UTC, TheShuEd commented
@DenaUxUi, вы планируете продолжать работу над этим?

2024-08-25 14:54 UTC, closed without merging