Two new spells of light
crystallpunk-14/crystall-punk-14 pull request #404
Opened 2024-08-09 13:27 UTC by Nimfar11

## About the PR

Adds two new light spells:
- Sphere of Light - creates a strong light source that you can bind to yourself.
- Flash of Light - a spell that blinds everyone in the flash area.

Добавляет два новых заклинания света:
- Сфера света - создает сильный источник света, который можно привязать к себе.
- Вспышка света - заклинание которое ослепляет всех в области вспышки.
Также перевел все заклинания на русский.

## Why / Balance

The more possibilities, the better.
Чем больше возможностей, тем лучше.

## Media

https://github.com/user-attachments/assets/7e781530-7712-43e4-8973-9856174bdc2f

2024-08-09 22:08 UTC, TheShuEd requested changes

2024-08-09 22:08 UTC, TheShuEd commented on Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
> +ent-CP14ActionSpellCureWounds = Лечить раны
```suggestion
ent-CP14ActionSpellCureWounds = Лечение ран
```

2024-08-09 22:08 UTC, TheShuEd commented on Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
> +ent-CP14ActionSpellCureWounds = Лечить раны
и в целом локализацией можно не париться вручную, у нас есть автотулза для этого, которую я отдельным пром использую

2024-08-09 22:08 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Actions/Spells/flash_light.yml
> +    color: "#e9e035"
давай для заклинаний света чисто белый цвет, или с оттенком в голубоватый

2024-08-10 09:55 UTC, Nimfar11 commented on Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
> +ent-CP14ActionSpellCureWounds = Лечить раны
поправил. Ну, пусть уже тогда будет раз сделал, или она мешает?

2024-08-10 09:56 UTC, Nimfar11 commented on Resources/Prototypes/_CP14/Entities/Actions/Spells/flash_light.yml
> +    color: "#e9e035"
Поправил цвет

2024-08-10 10:08 UTC, TheShuEd approved these changes

2024-08-10 10:08 UTC, merged