Content pack jr
crystallpunk-14/crystall-punk-14 pull request #457
Opened 2024-09-24 17:28 UTC by Jaraten

- add Gobby
- reconstruct Gobby
- redesign Gobby
- remove Gobby
- return Gobby
- recode Gobby
- delete Gobby
- [x] Gobby

2024-09-24 17:30 UTC, Jaraten commented
no Gobby were harmed.

2024-09-24 21:39 UTC, TheShuEd requested changes
а теперь нормальный чейнджлог всех изменений, с примерами скринов, которые я смогу вставлять в чейнджлоги в дискорде

2024-09-25 09:31 UTC, TheShuEd approved these changes

2024-09-25 09:31 UTC, merged

2024-09-25 11:41 UTC, Jaraten commented
@TheShuEd чек описание.

2024-09-25 11:54 UTC, TheShuEd commented
все гуд