Adding the sinner's mask
crystallpunk-14/crystall-punk-14 pull request #97
Opened 2024-04-15 17:45 UTC by Agoichi

## About the PR
New mask, blocks identity, nothing more

## Why / Balance
We need it. Mostly for the guardians who'll be executioner

## Technical details

## Media

![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/92464780/2c1e6c1b-0e74-4f3f-bdc2-185ef98a971a)
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/92464780/660e8209-696b-46ff-a03c-82880129baea)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The Sinner's Mask

2024-04-15 20:14 UTC, Agoichi commented
Что не так блять, ЧТО НЕ ТАК-ТО БЛЯТЬ ЕБАННЫЙ УБУНТУ

2024-04-16 04:09 UTC, TheShuEd requested changes

2024-04-16 04:09 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Clothing/Masks/pluto-mask.yml
> +  parent: ClothingMaskBase
Add CPBaseMask, with equip time and unequip time

2024-04-16 04:09 UTC, TheShuEd commented on Resources/Prototypes/_CP14/Entities/Clothing/Masks/pluto-mask.yml
> +  name: Маска Грешника
Eng name and description 
+ Localization in separate file

2024-04-16 13:39 UTC, Agoichi commented
Done

2024-04-16 13:41 UTC, Agoichi commented
блять

2024-04-16 13:52 UTC, TheShuEd approved these changes

2024-04-16 13:52 UTC, Agoichi commented
Тест Убунбу для дуракав

2024-04-16 13:56 UTC, Deserty0 commented
ты бы со всей локализацией сделал так

2024-04-16 14:51 UTC, merged